### ISSUE TITLE
remplacer le jeux tetris en flash par une video

### ISSUE THREAD

**Issue by paulgirard** [medialab/mango_cognitive#1]
Dans la partie NRJ > jeu 1 > bloc 1
il y a un jeux flash Tetris.
il faut le remplacer par une vidéo http://youtube.com/lavideo

**Comment by adanon2015** [comment]
Dans NRJ > Jeu 1- Bloc 1, il faut remplacer le jeu flash Tetris par :
Cyprien - Les vieux et la technologie : https://www.youtube.com/watch?v=uFpKj3JbORs
Dans NRJ > Jeu 1 - Bloc 2, il faut remplacer le jeu flash Tetris par :
Kendji Girac - Andalouse - Live : https://www.youtube.com/watch?v=TyUPlPFbuLU
Dans NRJ > Jeu 1- Bloc 3, il faut remplacer le jeu flash Tetris par: 
Astérix et Obélix Mission Cléopâtre- Extrait : https://www.youtube.com/watch?v=LJQVGQ3llrg
Dans NRJ > Jeu 1- Bloc 4, il faut remplacer le jeu flash Tetris par: 
Katy Perry -  SuperBowl 2015: https://www.youtube.com/watch?v=ob3foW1wRF4
Dans NRJ > Jeu 1- Bloc 5, il faut remplacer le jeu flash Tetris par: 
Kev Adams – L’ado (en coupant si possible à 5 min47) : https://www.youtube.com/watch?v=QsrJ7CTr6wA

Les noms à mettre dans le menu déroulant sont :
Cyprien - Les vieux et la technologie
Kendji Girac - Andalouse - Live
Astérix et Obélix Mission Cléopâtre- Extrait
Katy Perry -  SuperBowl 2015
Kev Adams – L’ado

**Comment by Yomguithereal** [comment]
Videos téléchargées. Intégration en cours.

**Comment by Yomguithereal** [comment]
Note: Vidéo non coupée.

**Comment by Yomguithereal** [comment]
Vidéo coupée.
