### ISSUE TITLE
NRJ > jeu 1 > tous les blocs : problème affichage vidéo sur tablette

### ISSUE THREAD

**Issue by paulgirard** [medialab/mango_cognitive#2]
Quand on sélectionne une vidéo, ça marche.
Quand on change la sélection pour voir une autre vidéo, la nouvelle vidéo se place hors de l'écran.

Problème uniquement sur la tablette Asus Memopad 10 avec le navigateur boatbrowser.

**Comment by adanon2015** [comment]
La taille de la vidéo est trop grande: elle se superpose sur les boutons "faire des soustractions" et "regarder une vidéo" qu'on ne peut plus sélectionner
